var PlayingSongConstants = {
  PLAY_SONG: "PLAY_SONG",
  PAUSE_SONG: "PAUSE_SONG",
  NEW_SONG: "NEW_SONG",
  PLAY_PAUSE: "PLAY_PAUSE",
  NEXT_SONG: "NEXT_SONG",
  LAST_SONG: "LAST_SONG",
  NEW_PLAYLIST: "NEW_PLAYLIST",
  TOGGLE_MUTE: "TOGGLE_MUTE",
  SEEK_TO: "SEEK_TO"
};

module.exports = PlayingSongConstants;
