var PlaylistConstants = {
  ADD_SONG_TO_PLAYLIST: "ADD_SONG_TO_PLAYLIST",
  ADD_NEW_PLAYLIST: "ADD_NEW_PLAYLIST",
  REMOVE_SONG_FROM_PLAYLIST: "REMOVE_SONG_FROM_PLAYLIST"
};

module.exports = PlaylistConstants;
