var SongConstants = {
  USER_SONGS_RECEIVED: "USER_SONGS_RECEIVED",
  SONG_RECEIVED: "SONG_RECEIVED",
  SONGS_RECEIVED: "SONGS_RECEIVED",
  NUM_PLAYS_RECEIVED: "NUM_PLAYS_RECEIVED"
};

module.exports = SongConstants;
